### ISSUE TITLE
LPC.dll调用

### ISSUE THREAD

**Issue by wang-b22** [FACEGOOD/Voice2Face#15]
请问能提供一下Mac版本的吗，Win编译基本没用过，感谢🙏

**Comment by SZNero** [comment]
we have supply the LPC source code in code/LPC .You can compile according to different platform requirements

**Comment by birdflies** [comment]
> 请问能提供一下Mac版本的吗，Win编译基本没用过，感谢🙏

您好，请问你在mac上编译成功没？

**Comment by FishWoWater** [comment]
@birdflies @wang-b22 请问您编译成功了吗

**Comment by ankye** [comment]
可以提供个makefile文件吗？
